# Generated by Django 2.2.3 on 2022-01-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='register_info',
        ),
    ]
