# Generated by Django 2.2.3 on 2022-01-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0002_auto_20220125_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_info',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
