# Generated by Django 4.0 on 2022-02-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0003_auto_20220129_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='upload/product')),
            ],
        ),
    ]
